//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientConnectModelContainer : DbContext
    {
        public ClientConnectModelContainer()
            : base("name=ClientConnectModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Switch> SwitchSet { get; set; }
        public virtual DbSet<PbxConnection> PbxConnectionSet { get; set; }
        public virtual DbSet<KolanConnection> KolanConnectionSet { get; set; }
        public virtual DbSet<TelnetConnection> TelnetConnectionSet { get; set; }
        public virtual DbSet<File> FileSet { get; set; }
    }
}
