//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Switch()
        {
            this.File = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public string CrmNum { get; set; }
        public string Comments { get; set; }
        public string Name { get; set; }
        public string SwRelease { get; set; }
        public string MachineType { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Tid { get; set; }
    
        public virtual PbxConnection PbxConnection { get; set; }
        public virtual KolanConnection KolanConnection { get; set; }
        public virtual TelnetConnection TelnetConnection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> File { get; set; }
    }
}
